inital master node

diff --git a/ansible/roles/rocky_k8s_init/tasks/05_smoke_test.yml b/ansible/roles/rocky_k8s_init/tasks/05_smoke_test.yml
--- a/ansible/roles/rocky_k8s_init/tasks/05_smoke_test.yml
+++ b/ansible/roles/rocky_k8s_init/tasks/05_smoke_test.yml
@@ -172,43 +172,44 @@
   delegate_to: localhost
   run_once: true
   environment:
-    KUBECONFIG: "/home/{{ lookup('env', 'USER') }}/.kube/config"
+    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config"
   ansible.builtin.shell: |
     kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort} {.spec.ports[?(@.name=="https")].nodePort}'
   register: discovered_nodeports
 
-- debug:
-    var: discovered_nodeports.stdout_lines
-
-- name: 5.5.5 - Generate Config Fragment on Helper
+- name: 5.5.5 - Generate Unique Service Fragment
   delegate_to: localhost
   run_once: true
   ansible.builtin.template:
-    src: "k8s-cluster.cfg.j2"
+    src: "roles/rocky_k8s_init/templates/k8s-cluster.cfg.j2"
     dest: "/tmp/ingress-nginx-controller.cfg"
   vars:
-    # Splitting the stdout into a list: index 0 is http, index 1 is https
+    svc_name: "ingress-nginx"
     ingress_http_nodeport: "{{ discovered_nodeports.stdout.split()[0] | trim }}"
     ingress_https_nodeport: "{{ discovered_nodeports.stdout.split()[1] | trim }}"
 
-- name: 5.5.6 - Push and Move Service Fragment to LBs
+- name: 5.5.6 - Push and Swap Dummy for Real Service
   delegate_to: localhost
   loop: "{{ groups['hahost'] }}"
   vars:
     ssh_opts: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ssh_key_path }}"
     target_ip: "{{ hostvars[item].ansible_host }}"
   ansible.builtin.shell: |
-    # 1. SCP to /tmp first (since core user cannot write to /etc/haproxy directly)
+    # 1. SCP the real service config
     scp {{ ssh_opts }} /tmp/ingress-nginx-controller.cfg core@{{ target_ip }}:/tmp/ingress-nginx-controller.cfg
 
-    # 2. Move to final destination and set proper system permissions
+    # 2. Cleanup and Move
     ssh {{ ssh_opts }} core@{{ target_ip }} "
+      # Remove the dummy startup file to free up the ports/names
+      sudo rm -f /etc/haproxy/conf.d/k8s-cluster.cfg
+      
+      # Move real service into place
       sudo mv /tmp/ingress-nginx-controller.cfg /etc/haproxy/conf.d/ingress-nginx-controller.cfg
       sudo chown root:root /etc/haproxy/conf.d/ingress-nginx-controller.cfg
       sudo chmod 644 /etc/haproxy/conf.d/ingress-nginx-controller.cfg
     "
 
-- name: 5.5.7 - Remote Validation and Reload
+- name: 5.5.7 - Validate and Reload
   delegate_to: localhost
   loop: "{{ groups['hahost'] }}"
   vars:
@@ -216,17 +217,12 @@
     target_ip: "{{ hostvars[item].ansible_host }}"
   ansible.builtin.shell: |
     ssh {{ ssh_opts }} core@{{ target_ip }} "
-      # Validate the full config (Main + all fragments in conf.d)
       if sudo /usr/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/conf.d/; then
-        echo 'Configuration valid for {{ item }}, reloading HAProxy...'
         sudo systemctl reload haproxy
       else
-        echo 'CRITICAL: HAProxy configuration merge failed on {{ item }}'
-        exit 1
+        echo 'Validation Failed' && exit 1
       fi
     "
-  register: lb_reload_status 
-
 # - debug:
 #     var: haproxy_config_output.stdout_lines
 
